pub enum Instruction {
    C00E0,
    C00EE,
    C1NNN(u16),
    C2NNN(u16),
    C3XNN(usize, u8),
    C4XNN(usize, u8),
    C5XY0(usize, usize),
    C6XNN(usize, u8),
    C7XNN(usize, u8),
    C8XY0(usize, usize),
    C8XY1(usize, usize),
    C8XY2(usize, usize),
    C8XY3(usize, usize),
    C8XY4(usize, usize),
    C8XY5(usize, usize),
    C8XY6(usize, usize),
    C8XY7(usize, usize),
    C8XYE(usize, usize),
    C9XY0(usize, usize),
    CANNN(u16),
    CBNNN(u16),
    CCXNN(usize, u8),
    CDXYN(usize, usize, u8),
    CEX9E(usize),
    CEXA1(usize),
    CFX07(usize),
    CFX0A(usize),
    CFX15(usize),
    CFX18(usize),
    CFX1E(usize),
    CFX29(usize),
    CFX33(usize),
    CFX55(usize),
    CFX65(usize),
}
