name: Node.js Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - run: wasm-pack build --scope ${{ GITHUB_REPOSITORY_OWNER }} -- --features wasm
      - run: cd pkg
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
